### ISSUE TITLE
current page

### ISSUE THREAD

**Issue by vendveri** [vendveri/venveri#9]
have a simple issue and maybe I'm overthinking it, but I want to style the navbar differently on contact vs home. Simple enough concept but with Gatsby I'm stuck. Every page has the `location` where you can find the path of the page but he navbar is not a page. I tried importing react-react router and using it's globalHistory and get the page but when I click on the nav it doesn't update, In version 1 of Gatby the layout component was far different but with v2 the Layout is just like any other component.
At the end of the day I want to label a page with a call to style the navbar differently if it is the contact page. This was a rabbit hole for me today. Learned a lot about Gatsby in the process but still the contact page at scroll zero is invisible. TBC...

**Comment by anthonyrivas** [comment]
I have some thoughts on this, I was planning the same thing honestly. I'll give it a go tonight and see what I can do!

**Comment by anthonyrivas** [comment]
This was solved with the nav overhaul, though would still be cool to find a good solution.
